name: deploy test
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: make key
        run: echo "$SSH_KEY" > key && chmod 600 key
        env: 
            SSH_KEY:  ${{secrets.SSH_KEY}}
      - name: deploy
        run: rsync -avP -e "ssh -i ./key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p ${SSH_PORT} " ./public ${SSH_USER}@${SSH_IP}:tools
        env: 
            SSH_PORT: ${{secrets.SSH_PORT}}
            SSH_USER: ${{secrets.SSH_USER}}
            SSH_IP :  ${{secrets.SSH_IP}}
